### ISSUE TITLE
Question: ¿How to disable icon animation on modern theme?

### ISSUE THREAD

**Issue by jatubio** [craftpip/jquery-confirm#322]
Hello, I'm using your library and it's awesome!

**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[X ] support request

**Current behavior:**
I'm using 'modern' theme with font aweson icons. On showing dialog, icon is showed with a zoom animation.

**Expected behavior:**
¿There are some config option to disable this animation? Thank You!

**Comment by craftpip** [comment]
Sorry for the late reply
use:
```css
.jconfirm.jconfirm-modern .jconfirm-box div.jconfirm-title-c .jconfirm-icon-c {
  -webkit-transform: scale(1);
          transform: scale(1);
}
```
