### ISSUE TITLE
I'm getting confirm box in the center. How to make it appear at the top? 

### ISSUE THREAD

**Issue by meghalk** [craftpip/jquery-confirm#365]
**jquery-confirm version:**
v3.x.x

**I'm submitting a ...**  (check one with "x")
[ ] bug report
[ ] feature request
[ ] support request

**Current behavior:**

**Expected behavior:**

**Steps to reproduce:**

**Related code:**
```
insert any relevant code here
```

**Other information:**

**Comment by craftpip** [comment]
This functionality is not supported, 
but if u still want the popup to be placed in top use this CSS
```css
.jconfirm .jconfirm-cell {
    vertical-align: top !important;
}
```
and set `animateFromElement` to `false`
