### ISSUE TITLE
Styling the header of the alert and confirm box

### ISSUE THREAD

**Issue by thesammit** [craftpip/jquery-confirm#64]
Styling of the confirm box or alert box header can be used by accepting an attribute to set the class for the modal header. This will give a better meaning to the functionality performed, especially on alerts.

The following needs to be Modified : 
[jquery-confirm.js]
[Modify]

``` javascript
421: this.$title.attr('id', jcr); else if (this.$content) //To
421: this.$title.attr('id', jcr).addClass(this.titleClass); else if (this.$content)
```

[Add]

``` javascript
434: titleClass:'',
```

[jquery-confirm.css]
[Add]

``` css
//Using bootstrap danger-title
.jconfirm .jconfirm-box div.danger {
    background-color: #e51c23;
    border-radius: 4px 4px 0px 0px;
    color: white;    
}
//Using bootstrap success-title
.jconfirm .jconfirm-box div.success {
    background-color: #4caf50;
    border-radius: 4px 4px 0px 0px;
    color: white;    
}
//Using bootstrap primary-title
.jconfirm .jconfirm-box div.primary {
    background-color: #2196f3;
    border-radius: 4px 4px 0px 0px;
    color: white;    
}
//Using bootstrap info-title
.jconfirm .jconfirm-box div.info {
    background-color: #9c27b0;
    border-radius: 4px 4px 0px 0px;
    color: white;    
}
//Using bootstrap warning-title
.jconfirm .jconfirm-box div.warning {
    background-color: #ff9800;
    border-radius: 4px 4px 0px 0px;
    color: white;    
}
```
